spring:
  config:
    exploits-dir: ./content/generated
    wordpress-dir: ./content/wordpress
    max-time-test: 2 # min
    dockerhub:
      base-url: https://hub.docker.com
      max-page-size: 100
    exploit-db:
      base-url: https://www.exploit-db.com
      max-retry-next: 10
      update: true
    nist:
      base-url: https://services.nvd.nist.gov/rest/json/
      max-page-size: 100
    wordpress:
      plugin-svn: https://plugins.svn.wordpress.org
      theme-svn: https://themes.svn.wordpress.org

logging:
  level:
    com.lprevidente.cve2docker.service: debug