version: '2'
services:
  joomla:
    image: joomla:3.9.24
    volumes:
      - ./config/joomla/configuration.php:/var/www/html/configuration.php
      - ./config/joomla/install-joomla-extension.php:/var/www/html/cli/install-joomla-extension.php
      - ./config/joomla/mysql:/var/www/html/installation/sql/mysql
    links:
      - db:mysql
    ports:
      - 80:80
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: root
      JOOMLA_DB_NAME: joomla
  db:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    environment:
      MYSQL_DATABASE: joomla
      MYSQL_ROOT_PASSWORD: root
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    links:
      - db:db