version: '3'
services:
  wp:
    image: wordpress:${WORDPRESS_VERSION}
    restart: 'always'
    ports:
      - 80:80
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    links:
      - db
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - 8080:80
    links:
      - db:db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
#    command: [
#        '--default_authentication_plugin=mysql_native_password',
#        '--character-set-server=utf8mb4',
#        '--collation-server=utf8mb4_unicode_ci'
#    ]
  wpcli:
    image: wordpress:cli
    user: xfs
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - wp-app:/var/www/html
    depends_on:
      - db
      - wp
volumes:
  wp-app:

